name: Build MESTool
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: (Opsional) Restore NuGet
        run: nuget restore MESTool.sln
      - name: Build Release
        run: msbuild MESTool.sln /p:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MESTool
          path: MESTool/bin/Release/
